- name: start zsh installed by homebrew
  command: /usr/local/bin/zsh

# Reference https://blog.ismg.kdl.co.jp/tools/zsh-prezto
- name: install prezto
  - git:
    repo: 'https://github.com/sorin-ionescu/prezto.git'
    dest: ~/.zprezto

- name: setup prezto
  command: setopt EXTENDED_GLOB for rcfile in ~/.zprezto/runcoms/^README.md(.N); do ln -s "$rcfile" "~/.${rcfile:t}" done

- name: move .zshrc to home directory
  copy:
    src: ../files/.zshrc
    dest: ~/.zshrc
    mode: 0644

- name: set zsh as default shell
  command: chsh -s '/usr/local/bin/zsh'

- name: source .zshrc
  command: source ~/.zshrc