- name: start zsh installed by homebrew
  command: /usr/local/bin/zsh

# Reference https://blog.ismg.kdl.co.jp/tools/zsh-prezto
- name: install prezto
  git:
    repo: 'https://github.com/sorin-ionescu/prezto.git'
    dest: ~/.zprezto

- name: setup prezto
  file:
    src: '~/.zprezto/runcoms/{{ item.src }}'
    dest: '~/{{ item.dest }}'
    state: link
  with_items:
    - { src: 'zlogin', dest: '.zlogin' }
    - { src: 'zlogout', dest: '.zlogout' }
    - { src: 'zpreztorc', dest: '.zpreztorc' }
    - { src: 'zprofile', dest: '.zprofile' }
    - { src: 'zshenv', dest: '.zshenv' }
    - { src: 'zshrc', dest: '.zshrc' }

- name: move .zshrc to home directory
  copy:
    src: ../files/.zshrc
    dest: ~/.zshrc
    mode: 0644

- name: set zsh as default shell
  command: chsh -s '/usr/local/bin/zsh'

- name: source .zshrc
  command: source ~/.zshrc