- name: Creates directory alacritty
  file:
    path: ~/.config/alacritty
    state: directory

- name: copy alacritty.yml to ~/.config/alacritty
  copy:
    src: ../files/alacritty.yml
    dest: ~/.config/alacritty/alacritty.yml
    mode: 0644
