# Reference https://github.com/RVIRUS0817/ansible_Mac

- name: Copy home directory .cache/dein
  file: path={{ item.name }} 
        state=directory 
        mode=0755
  with_items:
  - { name: '~/.cache/dein' }

- name: Download dein.vim install.sh
  get_url:
    url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
    dest: ~/.config/nvim
    mode: 0755
 
- name: install.sh dein.vim
  shell: sh ~/.config/nvim/installer.sh ~/.cache/dein

- name: source ~/.zshrc
  shell: source ~/.zshrc