# Reference https://github.com/RVIRUS0817/ansible_Mac

- name: Copy home directory .cache/dein
  file: path={{ item.name }} 
        state=directory 
        mode=0755
  with_items:
  - { name: '~/.cache/dein' }

- name: make .config directory
  file: path=~/.config state=directory mode=0700

- name: make .cache directory
  file: path=~/.cache state=directory mode=0755

- name: Download dein.vim install.sh
  get_url:
    url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
    dest: ~/.config/installer.sh
    mode: 0755
 
- name: install.sh dein.vim
  shell: sh ~/.config/installer.sh ~/.cache/dein
