- name: copy .ttf files to ~/Library/Fonts
  copy: src=../files/{{ item }} dest=~/Library/Fonts/
  with_items:
    - Cica-Bold.ttf
    - Cica-Regular.ttf
    - Cica-BoldItalic.ttf
    - Cica-RegularItalic.ttf
